### ISSUE TITLE
Integrate coffeescope to catch unused variables

### ISSUE THREAD

**Issue by petrosagg** [resin-io/resin-lint#5]
https://github.com/za-creature/coffeescope

**Comment by lekkas** [comment]
Nice find 👍 

I've played with it a bit and extended it a bit to catch for both unused and undefined variables; it has uncovered some potential issues in our codebase.

However both checks have some false positives, and in the case of catching use of undefined variables we'll probably have to include an extra coffeelint.json to suppress warnings in some projects (e.g. the UI) though I'd like to avoid this if possible.

In any case, as a first step I'm submitting a PR to show warnings for unused variables and I'll also open an issue to the coffeescope for the false positive edge cases I found.

**Comment by lekkas** [comment]
Discussion on the false positive alarms - https://github.com/za-creature/coffeescope/issues/17

**Comment by za-creature** [comment]
Hi, I'm the coffeescope2 maintainer

Not sure what you guys are doing here, but if you have any extra false positives, send 'em my way :)

**Comment by lekkas** [comment]
Hey @za-creature,

We are integrating `coffeescope2` in our in-house coffeelint wrapper.

Thanks again for the lighting-fast fix on that false positive, we'll definitely send more feedback or issues as we go :)
